server:
  addr: :4444
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
database:
  name: postgres
  host: localhost # env DB_HOST
  port: 5432
  user: postgres
  password: postgres
traffic_api:
  authKey: # env TRAFFIC_API_AUTH_KEY
  url: https://api.trafikinfo.trafikverket.se/v2/data.json
mail:
  from: # env MAIL_USERNAME
  password: # env MAIL_PASSWORD
  smtpHost: poczta.o2.pl
  smtpPort: 465