server:
  addr: :8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
database:
  name: slmonitor
  host: localhost # env DB_HOST
  port: 5432
  user: slmonitor-user
  password: slmonitor-pwd
cache:
  host: localhost # env CACHE_HOST
  port: 6379
traffic_api:
  authKey: # env TRAFFIC_API_AUTH_KEY
  url: https://api.trafikinfo.trafikverket.se/v2/data.json
mail:
  from: # env MAIL_USERNAME
  password: # env MAIL_PASSWORD
  smtpHost: poczta.o2.pl
  smtpPort: 465