# This workflow will build a Docker image with SL Monitor, push it to Container Registry and then deploy to Cloud Run

name: Build and push Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/808738102708/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github@slmonitor.iam.gserviceaccount.com'

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
          project_id: slmonitor

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get latest git tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --abbrev=0 --tags)

      - name: Set semantic version
        run: |
          VERSION=$(echo ${LATEST_TAG} | awk -F'[.-]' '{printf "%d.%d.%d", $1, $2, $3+1}')
          echo "New version: ${VERSION}"

      - name: Build and tag Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            gcr.io/slmonitor/slmonitor-app:latest
            gcr.io/slmonitor/slmonitor-app:$VERSION

      - name: Push Docker image to Container Registry
        run: |
          docker push gcr.io/slmonitor/slmonitor-app:latest
          docker push gcr.io/slmonitor/slmonitor-app:$VERSION